language: python
matrix:
    include:
        - python: "2.6"
          env: TOXENV=py26
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.2"
          env: TOXENV=py32
        - python: "3.4"
          env: TOXENV=py34
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6-dev"
          env: TOXENV=py36
install:
    - pip install -r requirements-dev.txt
script:
    - tox -e ${TOXENV}
after_success:
    - coveralls